SOLVER:
  SEG_LOSS_FUNC: "GeneralizedBoundaryCombo"
  BCELOSS_WEIGHT: [1, 1]
  WB_AND_D_WEIGHT: [1, 1]
  WARMUP_FACTOR : 1.0
  BATCH_SIZE: 6
  LR: 1e-5
  NORM_SR_OUTPUT : "instance"
  TASK_LOSS_WEIGHT: 0.3
  MAX_ITER: 100000

MODEL:
  SCALE_FACTOR: 4
  DETECTOR_TYPE: "u-net16"
  UP_SAMPLE_METHOD: "pixel_shuffle"
  OPTIMIZER: 'Adam'

OUTPUT_DIR: 'output/exp1/20210827_GBC2_0.1'
