SOLVER:
  SEG_LOSS_FUNC: "Boundary" # Boundary
  BCELOSS_WEIGHT: [1, 1]
  WB_AND_D_WEIGHT: [1, 1]
  WARMUP_FACTOR : 1.0
  BATCH_SIZE: 6
  LR: 1e-5
  # ALPHA_MIN: 0.1
  # DECREASE_RATIO: 0.5
  NORM_SR_OUTPUT : "instance"
  TASK_LOSS_WEIGHT: 0.3
  MAX_ITER: 400000
  SR_PRETRAIN_ITER: 400000
  

MODEL:
  SCALE_FACTOR: 4
  DETECTOR_TYPE: "u-net16"
  UP_SAMPLE_METHOD: "pixel_shuffle"
  OPTIMIZER: 'Adam'
  FEAT_CAT: False
  # NUM_LAYERS_CENTER : 5

# DATASET:
#   TRAIN_IMAGE_DIR: 'datasets/crack_seg/train_ds_bicubic_4/images'
#   TRAIN_MASK_DIR : 'datasets/crack_seg/train_ds_bicubic_4/masks'

# INPUT:
#   IMAGE_SIZE: 112

OUTPUT_DIR: 'output/2021_3_25_case6_ss-sr_sr-pretrained' #2021_3_8_x1_Boundary_Adam_unet16_bs6_ds-x4_pixel-shuffle'
# DEVICE_NUM: 7
DEVICE: "cuda"
