SOLVER:
  SEG_LOSS_FUNC: "BoundaryCombo"
  BCELOSS_WEIGHT: [1, 1]
  WB_AND_D_WEIGHT: [1, 1]
  WARMUP_FACTOR : 1.0
  BATCH_SIZE: 6
  LR: 1e-5
  NORM_SR_OUTPUT : "instance"
  MAX_ITER: 100000

MODEL:
  SCALE_FACTOR: 1
  DETECTOR_TYPE: "u-net16"
  UP_SAMPLE_METHOD: "pixel_shuffle"
  OPTIMIZER: 'Adam'
  JOINT_LEARNING: False

OUTPUT_DIR: 'output/exp2/20210903_SS_in_HR'
